// Profile Types
export const SET_BIRTHDAY_IN_PROFILE = "SET_BIRTHDAY_IN_PROFILE";
export const SET_GENDER_IN_PROFILE = "SET_GENDER_IN_PROFILE";
export const CLEAR_PROFILE_DATA = "CLEAR_PROFILE_DATA";